name: jamiyati
description: Arabic offline monthly association manager.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  
  # الحزم المضافة للكشوفات والتقارير والتنبيهات الحديثة ومشاركة الصور
  pdf: ^3.10.8
  printing: ^5.11.1
  screenshot: ^3.0.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1

flutter:
  uses-material-design: true
